# Generated by Django 5.1 on 2026-04-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_contactmessage_alter_profile_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Shop Owner', 'Shop Owner'), ('Customer', 'Customer')], default=None, max_length=255, null=True),
        ),
    ]
